import { withOrgIdQuery } from "./auth";
import { mutation, internalMutation } from "./_generated/server";
import { v } from "convex/values";

export const getCurrent = withOrgIdQuery({
  handler: async (ctx, orgId) => {
    if (!orgId) return null;
    const podcast = await ctx.db
      .query("podcasts")
      .withIndex("by_orgId", (q) => q.eq("orgId", orgId))
      .first();
    return podcast ?? null;
  },
});

// Upsert a podcast for the authenticated org from feed metadata (includes imageUrl)
export const upsertFromFeed = mutation({
  args: {
    title: v.string(),
    description: v.optional(v.string()),
    websiteUrl: v.optional(v.string()),
    language: v.optional(v.string()),
    copyright: v.optional(v.string()),
    author: v.optional(v.string()),
    ownerName: v.optional(v.string()),
    ownerEmail: v.optional(v.string()),
    category: v.optional(v.string()),
    explicit: v.boolean(),
    imageUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity?.org_id) throw new Error("Not authenticated");
    const orgId = String(identity.org_id);
    const now = Date.now();

    const existing = await ctx.db
      .query("podcasts")
      .withIndex("by_orgId", (q) => q.eq("orgId", orgId))
      .first();

    const feedUrl = `/feeds/${orgId}.xml`;

    if (existing) {
      await ctx.db.patch(existing._id, {
        title: args.title,
        description: args.description,
        websiteUrl: args.websiteUrl,
        language: args.language,
        copyright: args.copyright,
        author: args.author,
        ownerName: args.ownerName,
        ownerEmail: args.ownerEmail,
        category: args.category,
        explicit: args.explicit,
        feedUrl,
        imageUrl: args.imageUrl ?? existing.imageUrl,
        lastUpdated: now,
      });
      return existing._id;
    }

    const id = await ctx.db.insert("podcasts", {
      orgId,
      title: args.title,
      description: args.description,
      feedUrl,
      websiteUrl: args.websiteUrl,
      language: args.language,
      copyright: args.copyright,
      author: args.author,
      ownerName: args.ownerName,
      ownerEmail: args.ownerEmail,
      category: args.category,
      explicit: args.explicit,
      imageUrl: args.imageUrl,
      imageFileId: undefined,
      lastUpdated: now,
    });
    return id;
  },
});

// Generate a temporary upload URL for podcast image uploads
export const generateUploadUrl = mutation({
  args: {},
  handler: async (ctx) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity?.org_id) throw new Error("Not authenticated");
    return ctx.storage.generateUploadUrl();
  },
});

export const upsertForOrg = mutation({
  args: {
    title: v.string(),
    description: v.optional(v.string()),
    // feedUrl is generated by the platform; not provided by clients
    websiteUrl: v.optional(v.string()),
    language: v.optional(v.string()),
    copyright: v.optional(v.string()),
    author: v.optional(v.string()),
    ownerName: v.optional(v.string()),
    ownerEmail: v.optional(v.string()),
    category: v.optional(v.string()),
    explicit: v.boolean(),
    // Optional new image file for cover art
    imageFileId: v.optional(v.id("_storage")),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity?.org_id) throw new Error("Not authenticated");
    const orgId = String(identity.org_id);
    const now = Date.now();

    const existing = await ctx.db
      .query("podcasts")
      .withIndex("by_orgId", (q) => q.eq("orgId", orgId))
      .first();

    // Compute a platform feed URL derived from org id
    const feedUrl = `/feeds/${orgId}.xml`;

    // If an image file was uploaded, compute a temporary public URL
    const imageUrl = args.imageFileId
      ? (await ctx.storage.getUrl(args.imageFileId)) ?? undefined
      : undefined;

    if (existing) {
      // Build a patch object that only sets image fields if provided
      const patch: Record<string, unknown> = {
        title: args.title,
        description: args.description,
        websiteUrl: args.websiteUrl,
        language: args.language,
        copyright: args.copyright,
        author: args.author,
        ownerName: args.ownerName,
        ownerEmail: args.ownerEmail,
        category: args.category,
        explicit: args.explicit,
        // Keep feedUrl in sync with org
        feedUrl,
        lastUpdated: now,
      };
      if (args.imageFileId) {
        patch.imageUrl = imageUrl;
        patch.imageFileId = args.imageFileId;
      }
      await ctx.db.patch(existing._id, patch);
      return existing._id;
    }

    const id = await ctx.db.insert("podcasts", {
      orgId,
      title: args.title,
      description: args.description,
      feedUrl,
      websiteUrl: args.websiteUrl,
      language: args.language,
      copyright: args.copyright,
      author: args.author,
      ownerName: args.ownerName,
      ownerEmail: args.ownerEmail,
      category: args.category,
      explicit: args.explicit,
      imageUrl: imageUrl,
      imageFileId: args.imageFileId,
      lastUpdated: now,
    });
    return id;
  },
});

// Create a podcast for an organization from server-side events (e.g., webhooks).
// This bypasses user auth and can be invoked via ctx.runMutation(internal.podcasts.createFromOrg, ...)
export const createFromOrg = internalMutation({
  args: {
    orgId: v.string(),
    title: v.string(),
    imageUrl: v.optional(v.string()),
  },
  handler: async (ctx, { orgId, title, imageUrl }) => {
    const now = Date.now();

    const existing = await ctx.db
      .query("podcasts")
      .withIndex("by_orgId", (q) => q.eq("orgId", orgId))
      .first();

    const feedUrl = `/feeds/${orgId}.xml`;

    if (existing) {
      await ctx.db.patch(existing._id, {
        title,
        feedUrl,
        imageUrl: imageUrl ?? existing.imageUrl,
        lastUpdated: now,
      });
      return existing._id;
    }

    const id = await ctx.db.insert("podcasts", {
      orgId,
      title,
      description: undefined,
      feedUrl,
      websiteUrl: undefined,
      language: undefined,
      copyright: undefined,
      author: undefined,
      ownerName: undefined,
      ownerEmail: undefined,
      category: undefined,
      explicit: false,
      imageUrl,
      imageFileId: undefined,
      lastUpdated: now,
    });
    return id;
  },
});
